# Generated by Django 6.1 on 2026-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoanimal",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
